### ISSUE TITLE
Support multiple lights

### ISSUE THREAD

**Issue by rrooggiieerr** [rrooggiieerr/esphome-livingcolors1#3]
The lights react, however, it seems like they are reacting to a 'previous command'.

1. Turning on - nothing
2. Turning off - the lights turn on
3. Set a color - the light turns off
4. Set a different color - the light turns on and is set to the previously selected color
5. Set a different color - the light sets to the second selected color
6. ...

There should be a routine to double-send a command or something.

_Originally posted by @bn326160 in https://github.com/rrooggiieerr/esphome-livingcolors1/issues/2#issuecomment-2307271623_

**Comment by rrooggiieerr** [comment]
@bn326160 @Kaaf76 I think I fixed the issue with the weird behaviour when using multiple lights in the CC2500 component. Could you give that a try?

The new code also adds support for using the original remote, but I still need to do more testing and improve the documentation for that.

Use the following to use the latest code from GitHub (no `ref` argument and added `refresh` argument):
```
external_components:
  - source:
      type: git
      url: https://github.com/rrooggiieerr/esphome-cc2500
    components: [cc2500]
    refresh: 0s
  - source:
      type: git
      url: https://github.com/rrooggiieerr/esphome-livingcolors1
    components: [livingcolors1]
    refresh: 0s
```
