### ISSUE TITLE
3 living lights, that dont always recieve the command?

### ISSUE THREAD

**Issue by undeadalien1** [rrooggiieerr/esphome-livingcolors1#5]
hi,  i got 3 livingcolor lights, but they dont always seem to respond when i turn them on/off/change color.

```
button:
  - platform: livingcolors1
    address: 0x2FB8954C21B21054
    pair:
      name: "Pair LivingColors"
    unpair:
      name: "Unpair LivingColors"
  - platform: livingcolors1
    address: 0x0FC71B3221B21054
    pair:
      name: "Pair LivingColors2"
    unpair:
      name: "Unpair LivingColors2"
  - platform: livingcolors1
    address: 0xEC2D2C6A21B21054
    pair:
      name: "Pair LivingColors3"
    unpair:
      name: "Unpair LivingColors3"
light:
  - platform: livingcolors1
    name: "LivingColors"
    address: 0x2FB8954C21B21054
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: livingcolors1
    name: "LivingColors2"
    address: 0x0FC71B3221B21054
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: livingcolors1
    name: "LivingColors3"
    address: 0xEC2D2C6A21B21054
    restore_mode: RESTORE_DEFAULT_OFF
```

in homeassistant i added a lightgroup
```
type: light
entity: light.livinglights`
```
```
- platform: group
    name: livinglights
    entities:
      - light.esp_livinglights_livingcolors3
      - light.esp_livinglights_livingcolors2
      - light.esp_livinglights_livingcolors`
```
and when i use that group often only 1 or 2 listen.
also tried them invididualy but even then they sometimes need several "on/of" switches before they listen.

are the on/off commands the same? or could i set it up to send every command a few times to increase odds of all devises listening?

log
```
[06:58:45][D][light:036]: 'LivingColors' Setting:
[06:58:45][D][light:047]:   State: OFF
[06:58:45][W][component:237]: Component light took a long time for an operation (90 ms).
[06:58:45][W][component:238]: Components should block for at most 30 ms.
[06:58:45][D][light:036]: 'LivingColors2' Setting:
[06:58:45][D][light:047]:   State: OFF
[06:58:45][W][component:237]: Component light took a long time for an operation (89 ms).
[06:58:45][W][component:238]: Components should block for at most 30 ms.
[06:58:45][D][light:036]: 'LivingColors3' Setting:
[06:58:45][D][light:047]:   State: OFF
[06:58:45][W][component:237]: Component light took a long time for an operation (90 ms).
[06:58:45][W][component:238]: Components should block for at most 30 ms.
```
only 2 went off this time

using a D1mini and a blue cc2500"https://amzn.eu/d/fRXfjNN"

update: 
attempting to create fork"https://github.com/undeadalien1/esphome-livingcolors1" and play with repeat attempts, though i am no programmer xD  
hmm, after messing about with my own fork,  yours still seems to work best,
turned each lamp individualy on and off 10 times,  so 20 commands each
lamp1 responded 100% of the time
lamp 2 (has 4 pc screens inbetwean lamp/cc2500)  responded about 50% of the time
lamp 3, furthest responded less then 50% of the time
also orderd a antenna, but after rechecking my order i think i orderd the wrong one ;P "https://amzn.eu/d/3fQ2uWb"

**Comment by rrooggiieerr** [comment]
Hi! Good to hear my ESPHome External Component is being used. The problems you're facing probably has to do with the limited range of the CC2500 module. I don't have experience with the blue CC2500 module you're using, but with the green one I'm using and which is documented in the readme has a range of about 2 meters at best. I also have used an other blue CC2500 module but that one didn't perform any better.

How far are your lights from the ESP/CC2500 located?

The library repeats the command a couple of times. Default 7 times which is the same as the original LivingColors remote does. You can override the number of repeats for each ligt by adding `send_repeats: N` to the light configuration, where N is the number of repeats you like to send. Like this:

```
light:
  - platform: livingcolors1
    id: light1
    name: "LivingColors"
    address: 0x...
    send_repeats: 10
    restore_mode: RESTORE_DEFAULT_OFF
```

Let me know if that improves the situation
